[package]
name = "termtube"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
url = "2.5.2"

